version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filament-app
    restart: unless-stopped
    working_dir: /var/www
    env_file:
        - .env
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www
#      - /var/www/vendor
#      - /var/www/node_modules
    networks:
      - filament
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: filament-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - .docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - filament
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: filament-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
        - .env
    volumes:
      - .docker/postgresql/data:/var/lib/postgres/data
    networks:
      - filament

  redis:
    image: redis:alpine
    container_name: filament-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - filament

networks:
  filament:
    driver: bridge
